improve tensor pass example
outerbounds/metaflow-torchrun pull request #8
Opened 2024-12-28 13:54 UTC by madhur-ob

2025-01-03 21:00 UTC, valayDave requested changes
More questions than feedback.

2025-01-03 21:00 UTC, valayDave commented on examples/tensor-pass/script.py
> +        torch.distributed.barrier()
Why do you need to do this ? Whats the problem with using just `torch.distributed.barrier()`

2025-01-03 21:00 UTC, valayDave commented on examples/tensor-pass/script.py
> +        init_method=f"env://",
Why do we need to specify init_method ? What difference will it make if there is none?

2025-01-06 04:30 UTC, madhur-ob commented on examples/tensor-pass/script.py
> +        torch.distributed.barrier()
this is to avoid the following:

```
2024-12-28 18:45:01.480 [7647/torch_multinode/48735 (pid 71735)] [pod js-e61e42-control-0-0-nckw2] [rank0]:[W1228 13:15:01.899912212 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
```

2025-01-06 04:32 UTC, madhur-ob commented on examples/tensor-pass/script.py
> +        init_method=f"env://",
We can actually remove this I think, since it is the default too, I was just being more explicit

https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization

2025-01-06 04:39 UTC, madhur-ob commented on examples/tensor-pass/script.py
> +        torch.distributed.barrier()
posting again for better readability..

```
using GPU 0 to perform barrier as devices used by this process are currently unknown.
This can potentially cause a hang if this rank to GPU mapping is incorrect.
Specify device_ids in barrier() to force use of a particular device,
or call init_process_group() with a device_id.
```

2025-01-06 07:40 UTC, valayDave approved these changes

2025-01-06 07:43 UTC, merged